---
title: "SICSS Project"
author: Ela Castellanos-Reyes
date: '06-16-22'
output: html_notebook

---
# Prepare workspace
The project is already in my preferred working directory.
Regarding loading package pdftools: #When prompted if want to install from sources the packages whihc need compilation say NO. Explanation here https://community.rstudio.com/t/meaning-of-common-message-when-install-a-package-there-are-binary-versions-available-but-the-source-versions-are-later/2431  

```{r}
pacman::p_load(
  tidyverse,
  pdftools, 
  tesseract
)

setwd("/Users/Ela 1/Documents/LDT Mac/7. ProfessionalDevelopment/SICSS_Project/SICSS-Project-African-Youth-Leadership/Webscraped data")
#install.packages("pdftools")
#setwd(/Users/Ela 1/Documents/LDT Mac/7. ProfessionalDevelopment/SICSS_Project/)
```

I'm using this website as help https://www.r-bloggers.com/2018/01/how-to-extract-data-from-a-pdf-file-with-r/ 

```{r}
getwd()
```


```{r}
file_vector <- list.files(path = "/Users/Ela 1/Documents/LDT Mac/7. ProfessionalDevelopment/SICSS_Project/SICSS-Project-African-Youth-Leadership/Webscraped data")
#View(file_vector)
```

```{r}
results <- lapply(file_vector, pdf_text)
```




Only loading one doc. The result looks messy. 
```{r}
pdf_text("/Users/Ela 1/Documents/LDT Mac/7. ProfessionalDevelopment/SICSS_Project/Webscraped data/AYLS001_ALA.pdf") 
```
The code below separates by lines. 
```{r}
pdf_text("/Users/Ela 1/Documents/LDT Mac/7. ProfessionalDevelopment/SICSS_Project/Webscraped data/AYLS001_ALA.pdf")  %>% 
  strsplit(split = "\n") 
```










